#!/bin/bash

BASEDIR=${IN_DIR}/work/${RERUN}/${streamID}

echo "Merging registries..."

echo '${ROOT_SOFTS}/ImageProcessingPipelines/workflows/srs/pipe_scripts/merge_registries.sh "RAW2VISIT" "${BASEDIR}/task_ingestion/${streamID}/registries/registry_*.sqlite3" "${IN_DIR}/registry.sqlite3"'

${ROOT_SOFTS}/ImageProcessingPipelines/workflows/srs/pipe_scripts/merge_registries.sh "RAW2VISIT" "${BASEDIR}/task_ingestion/${streamID}/registries/registry_*.sqlite3" "${IN_DIR}/registry.sqlite3"
