#!/bin/bash

WORKDIR=${IN_DIR}/work/${RERUN}/${streamID}/calexp
mkdir -p ${WORKDIR}
export WORKDIR 


echo "merging registries in ${WORKDIR}/registries"
merge_registries.sh TRACT2VISIT "${WORKDIR}/registries/tracts_mapping*.sqlite3" ${OUT_DIR}/rerun/${RERUN1}/tracts_mapping.sqlite3


