#!/bin/bash

# Ready to ingest
export OMP_NUM_THREADS=1
if [[ $SITE == "NERSC" ]]
then
  ingestDriver.py ${NERSC_DRP_OUTPUT} @${VISIT_FILE} --cores 8 --mode link --batch-type none --output ${NERSC_DRP_OUTPUT} -c clobber=True allowError=True register.ignore=True
else
  ingestDriver.py ${IN_DIR} @${VISIT_FILE} --cores 8 -c clobber=True allowError=True register.ignore=True
fi
