#!/bin/bash
#
# Create the list of files to ingest

# Ready to ingest
export OMP_NUM_THREADS=1
if [[ $SITE == "NERSC" ]]
then
  mkdir -p ${NERSC_DRP_OUTPUT}
  cp ${SCRIPT_LOCATION}/../dm_configs/_mapper ${NERSC_DRP_OUTPUT}/
  ingestDriver.py ${NERSC_DRP_OUTPUT} @${VISIT_FILE} --cores 8 --mode link --batch-type none --output ${NERSC_DRP_OUTPUT} -c clobber=True allowError=True register.ignore=True
else
  # Make sure the output directory exists
  mkdir -p ${IN_DIR}
  # If the output directory does not contain a mapper file, create one
  cp ${SCRIPT_LOCATION}/../dm_configs/_mapper ${IN_DIR}/
  ingestDriver.py ${IN_DIR} @${VISIT_FILE} --cores 8 -c clobber=True allowError=True register.ignore=True
fi
