#!/bin/bash

# checkpoint
source ${SETUP_LOCATION}/checkpoint

if [[ -z "${INGESTDATA}" ]];
then
  # Ready to ingest
  export OMP_NUM_THREADS=1
  if [[ $SITE == "NERSC" ]]
  then
    ingestDriver.py ${IN_DIR} @${VISIT_FILE} --cores 8 --mode link --batch-type none --output ${IN_DIR} -c clobber=True allowError=True register.ignore=True --no-versions
  else
    ingestDriver.py ${IN_DIR} @${VISIT_FILE} --cores 16 -c clobber=True allowError=True register.ignore=True
  fi
fi
