#!/bin/bash

# checkpoint
source ${SETUP_LOCATION}/checkpoint

if [[ $RERUN = *":"* ]]; then
   IFS=":" read RERUN1 RERUN2 <<< $RERUN
else
   RERUN1=$RERUN
   RERUN2=$RERUN
fi
export RERUN1
export RERUN2

# Build the list of tracts/patches for the rings sky map
makeSkyMap.py ${IN_DIR} --rerun ${RERUN1}
