#!/bin/bash

### run metacalibration on the tract and set of patches provided as input

# checkpoint
source ${SETUP_LOCATION}/checkpoint

DC2PROD=${ROOT_SOFTS}/DC2-production/scripts
DPDD_DIR=${OUT_DIR}/dpdd/${RERUN}/metacal_table_summary
mkdir -p ${DPDD_DIR}
cmd="python ${DC2PROD}/merge_metacal_cat.py ${OUT_DIR}/rerun/${RERUN2} ${TRACT} --output_dir=${DPDD_DIR}"
echo $cmd;$cmd;
