#!/bin/bash

### run multiband on the tract and set of patches provided as input

if [[ $SITE == "LSST-IN2P3" ]]
then
    echo "launching monitoring script..... output will be under $(dirname ${SGE_STDOUT_PATH})"
    /pbs/home/d/descprod/bin/joremon.sh
fi

cmd="multiBandDriver.py ${OUT_DIR} --rerun ${RERUN2} --id tract=${TRACT} patch=${PATCH} filter=${FILTERS//,/^} --cores=$((NSLOTS+1)) --longlog --reuse-outputs-from  all"
echo $cmd;$cmd

