#!/bin/bash

### run metacalibration on the tract and set of patches provided as input

# checkpoint
source ${SETUP_LOCATION}/checkpoint

cmd="processDeblendedCoaddsNGMixMax.py ${OUT_DIR} --rerun ${RERUN} --id tract=${TRACT} patch=${PATCH} filter=g^r^i^z -C ${ROOT_SOFTS}/ImageProcessingPipelines/config/mcal-filters.py -C ${ROOT_SOFTS}/ImageProcessingPipelines/config/ngmix-deblended-bd.py"

echo $cmd;$cmd;

cmd="processDeblendedCoaddsMetacalMax.py ${OUT_DIR} --rerun ${RERUN} --id tract=${TRACT} patch=${PATCH} filter=g^r^i^z -C ${ROOT_SOFTS}/ImageProcessingPipelines/config/mcal-filters.py -C ${ROOT_SOFTS}/ImageProcessingPipelines/config/ngmix-deblended-mcalmax.py"

echo $cmd;$cmd;

echo \{\"job_type\":\"metacal\", \"stream_id\":\"${streamID}\", \"jobid\":\"${JOB_ID}\", \"logfile\":\"${JOBCONTROL_LOGFILE}\", \"release\":\"${DM_RELEASE}\",\"run\":\"${RUN}\",\"tag\":\"${SETUP_TAG}\",\"tract\":\"${TRACT}\",\"patch\":\"${PATCH}\"\} >> ${WORKDIR}/postcoadd_housekeeping.txt

DC2PROD=${ROOT_SOFTS}/DC2-production/scripts
DPDD_DIR=${OUT_DIR}/dpdd/${RERUN}/metacal_table_summary
mkdir -p ${DPDD_DIR}
cmd="python ${DC2PROD}/merge_metacal_cat.py ${OUT_DIR}/rerun/${RERUN2} ${TRACT} --patches=${PATCH} --output_dir=${DPDD_DIR}"
echo $cmd;$cmd;
