#!/bin/bash

if [[ -z ${DPDD_TAG} ]]; then
    DPDD_TAG=${RERUN}
fi
DPDD_DIR=${OUT_DIR}/dpdd/${DPDD_TAG}/source_table_summary
mkdir -p $DPDD_DIR

forcedPhotCcd.py ${IN_DIR} -j ${NSLOTS} --rerun ${RERUN} --id visit=${VISIT} --timeout 999999999 -C ${ROOT_SOFTS}/ImageProcessingPipelines/config/forcedPhotCcdConfig.py

echo "DPDD : generate files for source table in visit=${VISIT}"
DC2PROD="${ROOT_SOFTS}/DC2-production/scripts" 
echo python ${DC2PROD}/merge_source_cat.py "${OUT_DIR}/rerun/${RERUN2}" --visits ${VISIT} --output_dir=${DPDD_DIR}
python ${DC2PROD}/merge_source_cat.py "${OUT_DIR}/rerun/${RERUN2}" --visits ${VISIT} --output_dir=${DPDD_DIR}

