#!/bin/bash

if [[ $SITE == "LSST-IN2P3" ]]
then
    echo "launching monitoring script..... output will be under $(dirname ${SGE_STDOUT_PATH})"
    /pbs/home/d/descprod/bin/joremon.sh
fi

if [[ -z ${DPDD_TAG} ]]; then
    DPDD_TAG=${RERUN}
fi

DPDD_DIR=${OUT_DIR}/dpdd/${DPDD_TAG}/object_table_summary/
mkdir -p $DPDD_DIR

echo "DPDD : generate files for object table in tract=${TRACT}"

DC2PROD="${ROOT_SOFTS}/DC2-production/scripts"
#DPDD object catalog is fast to run, so we execute per tract in one shot
cmd="python ${DC2PROD}/make_object_catalog.py ${OUT_DIR}/rerun/${RERUN2} ${TRACT} -o ${TMPDIR}"
echo $cmd;$cmd;
mv ${TMPDIR}/object_${TRACT}*.parquet* ${DPDD_DIR}/

#merge
if ls ${DPDD_DIR}/object_${TRACT}*.parquet 1> /dev/null 2>&1; then
    if [ -f ${DPDD_DIR}/object_tract_${TRACT}.parquet ]; then
	rm ${DPDD_DIR}/object_tract_${TRACT}.parquet
    fi
    cmd="python ${DC2PROD}/merge_parquet_files.py ${DPDD_DIR}/object_${TRACT}_*.parquet -o ${DPDD_DIR}/object_tract_${TRACT}.parquet --assume-consistent-schema"
    echo $cmd;$cmd;
else
    echo "No files ${DC2PROD}/merge_parquet_files.py ${DPDD_DIR}/object_${TRACT}*.parquet found" 
fi
