#!/bin/bash

# checkpoint
source ${SETUP_LOCATION}/checkpoint


DM_SETUP=${DM_SETUP}
source ${SETUP_LOCATION}/DMsetup.sh
WORKDIR=${WORKDIR}/task_skycorrection/${streamID}
mkdir -p ${WORKDIR}

export OMP_NUM_THREADS=1
skyCorrection.py ${OUT_DIR}  --rerun ${RERUN} --id visit=${VISIT} --cores ${NSLOTS} --timeout 999999999
echo '{"pipe_step":"sky_correction", "jobid":"${JOB_ID}", "logfile":"${JOBCONTROL_LOGFILE}",  "release":"${DM_RELEASE}","run":"${RUN}","tag":"${SETUP_TAG}","visit":"${VISIT}"}' >> ${WORKDIR}/skycorrection_housekeeping.txt


