#!/bin/bash

if [[ $SITE == "LSST-IN2P3" ]]
then
    echo "launching monitoring script..... output will be under $(dirname ${SGE_STDOUT_PATH})"
    /pbs/home/d/descprod/bin/joremon.sh
fi

cmd="imageDifferenceDriver.py ${IN_DIR} --rerun ${RERUN} --id visit=${VISIT} -C ${DIA_PIPE_DIR}/config/imageDifferenceDriver.py --cores $((NSLOTS+1))"
echo $cmd;$cmd;
