#!/bin/bash

#launch the monitoring script
if [[ $SITE == "LSST-IN2P3" ]]
then
    echo "launching monitoring script..... output will be under $(dirname ${SGE_STDOUT_PATH})"
    /pbs/home/d/descprod/bin/joremon.sh
fi

echo "Working on TRACT=${TRACT}, PATH=${PATCH}, FILT=${FILT}"

visit_file=${FILEDIR}/${TRACT}_${PATCH}_${FILT}_visits.list 

if [[ -z $DIA_REF ]]; then
    echo "Executing coaddDriver for DRP coaddition"
    if [ $FILT = u ]; then
	echo "coaddDriver.py ${OUT_DIR} --rerun ${RERUN1}:${RERUN2}-u --id tract=${TRACT} patch=${PATCH} filter=$FILT @${visit_file} --cores $((NSLOTS+1)) --longlog --configfile=${OBS_LSST_DIR}/config/coaddDriver_noPSF.py"
	coaddDriver.py ${OUT_DIR} --rerun ${RERUN1}:${RERUN2}-u --id tract=${TRACT} patch=${PATCH} filter=$FILT @${visit_file} --cores $((NSLOTS+1)) --longlog --configfile=${OBS_LSST_DIR}/config/coaddDriver_noPSF.py
    else
	echo "coaddDriver.py ${OUT_DIR} --rerun ${RERUN1}:${RERUN2}-grizy --id tract=${TRACT} patch=${PATCH} filter=$FILT @${visit_file} --cores $((NSLOTS+1)) --longlog"
	coaddDriver.py ${OUT_DIR} --rerun ${RERUN1}:${RERUN2}-grizy --id tract=${TRACT} patch=${PATCH} filter=$FILT @${visit_file} --cores $((NSLOTS+1)) --longlog
    fi
else
    echo "Executing coaddDriver for DIA reference templates"
    if [ $FILT = u ]; then
	cmd="coaddDriver.py ${OUT_DIR} --rerun ${RERUN1}:${RERUN2}-u --id tract=${TRACT} patch=${PATCH} filter=$FILT @${visit_file} --cores $((NSLOTS+1)) --longlog --configfile=${DIA_PIPE_DIR}/config/coaddDriver_BestSeeing_noPSF.py"
	echo $cmd;$cmd;
    else
	cmd="coaddDriver.py ${OUT_DIR} --rerun ${RERUN1}:${RERUN2}-grizy --id tract=${TRACT} patch=${PATCH} filter=$FILT @${visit_file} --cores $((NSLOTS+1)) --longlog --configfile=${DIA_PIPE_DIR}/config/coaddDriver_BestSeeing.py"
	echo $cmd;$cmd;
    fi
fi
