#!/bin/bash

### run metacalibration on the tract and set of patches provided as input

if [[ $SITE == "LSST-IN2P3" ]]
then
    echo "launching monitoring script..... output will be under $(dirname ${SGE_STDOUT_PATH})"
    /pbs/home/d/descprod/bin/joremon.sh
fi

status=`verify_checkpoint run_deblended`
if [[ $status = 0 ]]; then
    echo "skipping bulge-disk ngmix fit and proceeding"
elif [[ $status = 1 ]]; then
    echo "halting at bulge-disk ngmix computation"
    exit 1
else
    cmd="processDeblendedCoaddsMetacalMax.py ${OUT_DIR} --rerun ${RERUN} --id tract=${TRACT} patch=${PATCH} filter=g^r^i^z -C ${ROOT_SOFTS}/ImageProcessingPipelines/config/mcal-filters.py -C ${ROOT_SOFTS}/ImageProcessingPipelines/config/ngmix-deblended-mcalmax.py"
    echo $cmd;$cmd;
fi

status=`verify_checkpoint run_ngmix`
if [[ $status = 0 ]]; then
    echo "skipping bulge-disk ngmix fit and proceeding"
elif [[ $status = 1 ]]; then
    echo "halting at bulge-disk ngmix computation"
    exit 1
else
    cmd="processDeblendedCoaddsNGMixMax.py ${OUT_DIR} --rerun ${RERUN} --id tract=${TRACT} patch=${PATCH} filter=g^r^i^z -C ${ROOT_SOFTS}/ImageProcessingPipelines/config/mcal-filters.py -C ${ROOT_SOFTS}/ImageProcessingPipelines/config/ngmix-deblended-bd.py"
    echo $cmd;$cmd;
fi

status=`verify_checkpoint run_metacal_dpdd`
if [[ $status = 0 ]]; then
    echo "skipping metacal dpdd catalog creation"
elif [[ $status = 1 ]]; then
    echo "halting at metacal dpdd catalog creation"
    exit 1
else
    DC2PROD="${ROOT_SOFTS}/DC2-production/scripts"
    DPDD_DIR=${OUT_DIR}/dpdd/${RERUN}/metacal_table_summary/
    mkdir -p $DPDD_DIR
    cmd="python ${DC2PROD}/make_metacal_catalog.py ${OUT_DIR}/rerun/${RERUN2} ${TRACT} -p ${PATCH} -o ${DPDD_DIR}"
    echo $cmd;$cmd;
fi

