#!/bin/bash

if [[ $SITE == "LSST-IN2P3" ]]
then
    echo "launching monitoring script..... output will be under $(dirname ${SGE_STDOUT_PATH})"
    /pbs/home/d/descprod/bin/joremon.sh
fi

DPDD_DIR=${OUT_DIR}/dpdd/${RERUN}/object_table_summary/
mkdir -p $DPDD_DIR

echo "DPDD : generate files for object table in tract=${TRACT}"

DC2PROD="${ROOT_SOFTS}/DC2-production/scripts"
#DPDD object catalog is fast to run, so we execute per tract in one shot
cmd="python ${DC2PROD}/make_object_catalog.py ${OUT_DIR}/rerun/${RERUN2} ${TRACT} -o ${DPDD_DIR}"
echo $cmd;$cmd;

#merge
cmd="python ${DC2PROD}/merge_parquet_files.py ${DPDD_DIR}/object_${TRACT}_*.parquet -o ${DPDD_DIR}/object_tract_${TRACT}.parquet --assume-consistent-schema"
echo $cmd;$cmd;

