#!/bin/bash

DM_SETUP=${DM_SETUP}
source ${SETUP_LOCATION}/DMsetup.sh
#WORKDIR=${WORKDIR}/task_calexp/${streamID}
export OMP_NUM_THREADS=1

mkdir -p ${WORKDIR}/registries/
export REGISTRIES="${WORKDIR}/registries"
pipelineSet REGISTRIES ${REGISTRIES}

verify_checkpoint () {
    var=`grep $1 ${CHECKPOINTS}`
    #check that process is not commented
    if [ "${var%${var#?}}"x != '#x' ]
    then
	local status=`echo ${var: -3:1}`
    else
	local status=""
    fi
    echo $status
}

status=`verify_checkpoint singleFrameDriver`
if [[ $status = 0 ]]; then
    echo "skipping singleFrameDriver and proceeding" 
elif [[ $status = 1 ]]; then
    echo "halting at singleFrameDriver" 
    exit 1
else
    echo "Running singleFrameDriver.py"
    if [[ -z "${RAFTNAME}" ]]; then
	singleFrameDriver.py ${IN_DIR} --rerun ${RERUN1} --id visit=${VISIT} --cores $((NSLOTS+1)) --timeout 999999999 --loglevel CameraMapper=warn
	echo '{'\"pipe_step\":\"singleFrameDriver\", \"jobid\":\"${JOB_ID}\", \"stream_id\":\"${streamID}\", \"logfile:\"${JOBCONTROL_LOGFILE}\", \"script\":\"${CUR_SCRIPT}\",  \"release\":\"${DM_RELEASE}\",\"run\":\"${RUN}\",\"tag\":\"${SETUP_TAG}\",\"visit\":\"${VISIT}\"'}' >> ${WORKDIR}/singleframe_housekeeping.txt
    else
	singleFrameDriver.py ${IN_DIR} --rerun ${RERUN1} --id visit=${VISIT} raftName=${RAFTNAME} --cores $((NSLOTS+1)) --timeout 99999999 --loglevel CameraMapper=warn
	echo '{'\"pipe_step\":\"singleFrameDriver\",\"jobid\":\"${JOB_ID}\", \"stream_id\":\"${streamID}\", \"logfile:\"${JOBCONTROL_LOGFILE}\", \"script\":\"${CUR_SCRIPT}\",  \"release\":\"${DM_RELEASE}\",\"run\":\"${RUN}\",\"tag\":\"${SETUP_TAG}\",\"visit\":\"${VISIT}\",\"raft\":\"${RAFTNAME}\"'}' >> ${WORKDIR}/singleframe_housekeeping.txt
    fi
    echo "Running checCcdAstrometry.py"
    ${ROOT_SOFTS}/ImageProcessingPipelines/python/util/checkCcdAstrometry.py ${IN_DIR}/rerun/${RERUN1} --id visit=${VISIT} --loglevel CameraMapper=warn

    echo "building mapper"
    ${ROOT_SOFTS}/ImageProcessingPipelines/python/util/tract2visit_mapper.py --indir=${IN_DIR}/rerun/${RERUN1} --db=${REGISTRIES}/tracts_mapping_${VISIT}.sqlite3 --visits=${VISIT}
fi


status=`verify_checkpoint skyCorrection`
if [[ $status = 0 ]]; then
    echo "skipping skyCorrection and proceeding"
elif [[ $status = 1 ]]; then
    echo "halting at skyCorrection"
    exit 1
else
    echo "Running skyCorrection.py"
    skyCorrection.py ${OUT_DIR}  --rerun ${RERUN} --id visit=${VISIT} --cores $((NSLOTS+1)) --timeout 999999999 --no-versions --loglevel CameraMapper=warn
    echo '{'\"pipe_step\":\"sky_correction\", \"jobid\":\"${JOB_ID}\", \"logfile\":\"${JOBCONTROL_LOGFILE}\",  \"release\":\"${DM_RELEASE}\",\"run\":\"${RUN}\",\"tag\":\"${SETUP_TAG}\",\"visit\":\"${VISIT}\"'}' >> ${WORKDIR}/skycorrection_housekeeping.txt
fi

