#!/bin/bash

# checkpoint
source ${SETUP_LOCATION}/checkpoint

mkdir -p ${WORK_DIR}/02-process

if [[ $RERUN = *":"* ]]; then
    IFS=":" read RERUN1 RERUN2 <<< $RERUN
else
    RERUN1=$RERUN
    RERUN2=$RERUN
fi
export RERUN1
export RERUN2

if [ ! -d "$IN_DIR/rerun/$RERUN1/deepCoadd" ]; then
    makeSkyMap.py ${IN_DIR} --output ${IN_DIR}/rerun/${RERUN1} --configfile ${CONFIGS_LOCATION}/makeSkyMapConfig.py
    #turn the absolute path into a relative one for the root entry in the yaml file, to ease shipping to NERSC
    sed -i -e 's+'${IN_DIR}'+..\/..+g' ${IN_DIR}rerun/$RERUN1/repositoryCfg.yaml
fi

build_singleframe_script () {
 cat> $1<<EOF
#!/bin/bash
DM_SETUP=${DM_SETUP}
source ${SETUP_LOCATION}/DMsetup.sh
export OMP_NUM_THREADS=1
singleFrameDriver.py ${IN_DIR} --rerun ${RERUN1} $2 --cores \${NSLOTS} --timeout 999999999
echo "Running checCcdAstrometry.py"
${ROOT_SOFTS}/ImageProcessingPipelines/python/util/checkCcdAstrometry.py ${IN_DIR}/rerun/${RERUN1} $2 --clobber-versions
${ROOT_SOFTS}/ImageProcessingPipelines/python/util/tract2visit_mapper.py --indir=${IN_DIR}/rerun/${RERUN1} --db=${IN_DIR}/rerun/${RERUN1}/tracts_mapping.sqlite3 --visits=$3
EOF
}

 
while read id; do
  IFS="=" read DUMMY1 DUMMY2 <<< $id
  if [ -z "${DUMMY2}" ]; then
      visit=$id #=$DUMMY1
      visit_cmd="--id visit=${visit}"
  else
      visit=$DUMMY2
      visit_cmd=$id
  fi
  echo $visit
  echo $visit_cmd
  if [[ $SITE == "LSST-IN2P3" ]]; then
    #build script with one visit per processing
    script="${WORK_DIR}/02-process/script_$visit.sh"
    build_singleframe_script "${script}" "${visit_cmd}" "${visit}"
    chmod a+x "${script}"
    # pipelineSet CUR_SCRIPT ${script} 
    pipelineCreateStream task_SingleFrameDriver -1 CUR_SCRIPT="${script}"
  else
    raft_list=`sqlite3 ${OUTPUT_DATA_DIR}/registry.sqlite3 'select distinct raftName from raw where visit=${visit}'`
    for raftName in $raft_list; do
        script="${WORK_DIR}/02-process/script_${raftName}_$visit.sh"
  	build_singleframe_script "${script}" "${id} raftName=${raftName}"
  	chmod a+x "${script}"
  	# pipelineSet CUR_SCRIPT ${script} 
  	pipelineCreateStream task_SingleFrameDriver -1 CUR_SCRIPT="${script}"
    done
  fi
  #one full complete visit at nersc or cc : run makeFpSummary
done < ${VISIT_FILE}

