#!/bin/bash

while read id; do
  IFS="=" read DUMMY1 DUMMY2 <<< $id
  if [ -z "${DUMMY2}" ]; then
      visit=$id #=$DUMMY1
      visit_cmd="--id visit=${visit}"
  else
      visit=$DUMMY2
      visit_cmd=$id
  fi
  pipelineSet VISIT $visit

  pipelineCreateStream task_forced_dia -1 VISIT="${visit}"
done < ${VISIT_FILE}

