#!/bin/bash

# checkpoint
source ${SETUP_LOCATION}/checkpoint

if [[ $RERUN = *":"* ]]; then
    IFS=":" read RERUN1 RERUN2 <<< $RERUN
else
    RERUN1=$RERUN
    RERUN2=$RERUN
fi
export RERUN1
export RERUN2

build_flat_script(){
 cat> $1<<EOF
#!/bin/bash
DM_SETUP=${DM_SETUP}
source ${SETUP_LOCATION}/DMsetup.sh
export OMP_NUM_THREADS=1
constructFlat.py ${OUT_DIR} --rerun ${RERUN} @$2 --cores \${NSLOTS}
EOF
}


mkdir -p ${OUT_DIR}/rerun/${RERUN1}/scripts



#     FLAT_FILE=`echo ${FILT}_FLAT_FILE`
#     echo $FLAT_FILE
    # while read visit_id; do
for FILT in $(echo ${FILTERS} | tr "," "\n"); do
    file=${OUT_DIR}/${FILT}_flat_visits.list
    echo $file
    script=${OUT_DIR}/rerun/${RERUN1}/scripts/master_flat_${FILT}.sh
    build_flat_script ${script} ${file}
    chmod a+x ${script}
    pipelineCreateStream task_flat -1 CUR_SCRIPT=${script}
done
    # done < ${FLAT_FILE}
# done

