#!/bin/bash

# checkpoint
source ${SETUP_LOCATION}/checkpoint

# WORKDIR="${WORK_DIR}/${streamID}"
# mkdir -p ${WORKDIR}

# if [[ $RERUN = *":"* ]]; then
#     IFS=":" read RERUN1 RERUN2 <<< $RERUN
# else
#     RERUN1=$RERUN
#     RERUN2=$RERUN
# fi
# export RERUN1
# export RERUN2

if [ ! -d "$IN_DIR/rerun/$RERUN1/deepCoadd" ]; then
    makeSkyMap.py ${IN_DIR} --rerun ${RERUN}
    #turn the absolute path into a relative one for the root entry in the yaml file, to ease shipping to NERSC
    #sed -i -e 's+'${IN_DIR}'+..\/..+g' ${IN_DIR}rerun/$RERUN1/repositoryCfg.yaml
fi

build_forcedphotccd_script () {
 cat> $1<<EOF
#!/bin/bash
DM_SETUP=${DM_SETUP}
source ${SETUP_LOCATION}/DMsetup.sh
export OMP_NUM_THREADS=1
forcedPhotCcd.py ${IN_DIR} -j \${NSLOTS} --rerun ${RERUN1} $2 --timeout 999999999 -c references.skipMissing=True
echo \${JOB_ID} ${visit} \${JOBCONTROL_LOGFILE} \${CUR_SCRIPT} >> ${IN_DIR}/forcedPhotCcd_housekeeping2.txt
EOF
}

 
while read id; do
  IFS="=" read DUMMY1 DUMMY2 <<< $id
  if [ -z "${DUMMY2}" ]; then
      visit=$id #=$DUMMY1
      visit_cmd="--id visit=${visit}"
  else
      visit=$DUMMY2
      visit_cmd=$id
  fi
  pipelineSet VISIT $visit

  if [[ $SITE == "LSST-IN2P3" ]]; then
    #build script with one visit per processing
    # script="${WORKDIR}/script_$visit.sh"
    # build_forcedphotccd_script "${script}" "${visit_cmd}" "${visit}"
    # chmod a+x "${script}"
    # pipelineCreateStream task_forcedPhotCcd -1 CUR_SCRIPT="${script}"
    pipelineCreateStream task_forced_ccd -1 VISIT="${visit}"
  else
    raft_list=`sqlite3 ${OUTPUT_DATA_DIR}/registry.sqlite3 'select distinct raftName from raw where visit=${visit}'`
    for raftName in $raft_list; do
        # script="${WORKDIR}/script_${raftName}_$visit.sh"
  	# build_forcedphotccd_script "${script}" "${id} raftName=${raftName}"
  	# chmod a+x "${script}"
  	# pipelineCreateStream task_forcedPhotCcd -1 CUR_SCRIPT="${script}",VISIT="${visit}"
  	pipelineCreateStream task_forced_ccd -1 VISIT="${visit}", ${RAFT}=${raftName}
    done
  fi
done < ${VISIT_FILE}

