#!/bin/bash

# checkpoint
source ${SETUP_LOCATION}/checkpoint

mkdir -p ${WORK_DIR}/20-diffim

if [[ $RERUN = *":"* ]]; then
    IFS=":" read RERUN1 RERUN2 <<< $RERUN
else
    RERUN1=$RERUN
    RERUN2=$RERUN
fi
export RERUN1
export RERUN2

if [ ! -d "$IN_DIR/rerun/$RERUN1/deepCoadd" ]; then
    echo "$IN_DIR/rerun/$RERUN1/deepCoadd" 
    echo "youhaveaproblem"
fi

build_imagedifference_script () {
 cat> $1<<EOF
#!/bin/bash
DM_SETUP=${DM_SETUP}
source ${SETUP_LOCATION}/DMsetup.sh
export OMP_NUM_THREADS=1
imageDifferenceDriver.py ${IN_DIR} --rerun ${RERUN1}:${RERUN2} $2 -C ${ROOT_SOFTS}/dia_pipe/config/imageDifferenceDriver.py --cores \${NSLOTS} --timeout 999999999
EOF
}

 
while read id; do
  IFS="=" read DUMMY1 DUMMY2 <<< $id
  if [ -z "${DUMMY2}" ]; then
      visit=$id #=$DUMMY1
      visit_cmd="--id visit=${visit}"
  else
      visit=$DUMMY2
      visit_cmd=$id
  fi
  echo $visit
  echo $visit_cmd
  if [[ $SITE == "LSST-IN2P3" ]]; then
    #build script with one visit per processing
    script="${WORK_DIR}/20-diffim/script_$visit.sh"
    build_imagedifference_script "${script}" "${visit_cmd}" "${visit}"
    chmod a+x "${script}"
    # pipelineSet CUR_SCRIPT ${script} 
    pipelineCreateStream task_ImageDifferenceDriver -1 CUR_SCRIPT="${script}"
  elif [[ $SITE == "NERSC" ]]; then
    #build script with one visit per processing
    script="${WORK_DIR}/20-diffim/script_$visit.sh"
    build_imagedifference_script "${script}" "${visit_cmd}" "${visit}"
    chmod a+x "${script}"
    # pipelineSet CUR_SCRIPT ${script} 
    pipelineCreateStream task_ImageDifferenceDriver -1 CUR_SCRIPT="${script}"
  else
    raft_list=`sqlite3 ${OUTPUT_DATA_DIR}/registry.sqlite3 'select distinct raftName from raw where visit=${visit}'`
    for raftName in $raft_list; do
        script="${WORK_DIR}/20-diffim/script_${raftName}_$visit.sh"
  	build_imagedifference_script "${script}" "${id} raftName=${raftName}"
  	chmod a+x "${script}"
  	# pipelineSet CUR_SCRIPT ${script} 
  	pipelineCreateStream task_ImageDifferenceDriver -1 CUR_SCRIPT="${script}"
    done
  fi
  #one full complete visit at nersc or cc : run makeFpSummary
done < ${VISIT_FILE}

