#!/bin/bash

BASEDIR=${IN_DIR}/work/${RERUN}/${streamID}
mkdir -p $BASEDIR
export BASEDIR

WORKDIR=${BASEDIR}/task_ingestion/${streamID}
mkdir -p ${WORKDIR}
export REGDIR=${WORKDIR}/registries
mkdir -p ${REGDIR}
export SCRDIR=${WORKDIR}/scripts
mkdir -p ${SCRDIR}
#pipelineSet REGDIR ${REGDIR}
#pipelineSet REGDIR ${SCRDIR}


if [ ! -f ${RAW_VISIT_FILE} ]; then
    echo "file ${RAW_VISIT_FILE} does not exist, exiting"
    exit 1
fi

VISITBASE=`basename ${RAW_VISIT_FILE} -s`
rm -f ${SCRDIR}/${VISITBASE}_chunk*

split -d -l ${RAW_CHUNKS} ${RAW_VISIT_FILE} ${SCRDIR}/${VISITBASE}_chunk

CHUNKFILES="${SCRDIR}/${VISITBASE}_chunk*"
cd ${SCRDIR}

for f in ${SCRDIR}/${VISITBASE}_chunk*
do
    pipelineCreateStream task_ingestData -1 CHUNKFILE=${f},REGDIR=${REGDIR},WORKDIR=${WORKDIR}
done


