#!/bin/bash

# checkpoint
source ${SETUP_LOCATION}/checkpoint

mkdir -p ${WORK_DIR}/02-process

build_singleframe_script () {
 cat> $1<<EOF
#!/bin/bash
DM_SETUP=${DM_SETUP}
source ${SETUP_LOCATION}/DMsetup.sh
export OMP_NUM_THREADS=1
singleFrameDriver.py ${IN_DIR} --rerun ${RERUN} $2 --cores \${NSLOTS} --timeout 999999999
echo "Running checCcdAstrometry.py"
${ROOT_SOFTS}/ImageProcessingPipelines/python/util/checCcdAstrometry.py ${IN_DIR}/rerun/${RERUN} $2 --clobber-versions
${ROOT_SOFTS}/ImageProcessingPipelines/python/util/tract2visit_mapper.py --indir=${IN_DIR}/rerun/${RERUN} --db=${IN_DIR}/rerun/${RERUN}/tracts_mapping.sqlite3 --visits=$3
EOF
}

 
while read id; do
  IFS="=" read DUMMY1 DUMMY2 <<< $id
  if [ -z "${DUMMY2}" ]; then
      visit=$id #=$DUMMY1
      visit_cmd="--id visit=${visit}"
  else
      visit=$DUMMY2
      visit_cmd=$id
  fi
  echo $visit
  echo $visit_cmd
  if [[ $SITE == "LSST-IN2P3" ]]; then
    #build script with one visit per processing
    script="${WORK_DIR}/02-process/script_${FILT}_$visit.sh"
    build_singleframe_script "${script}" "${visit_cmd}" "${visit}"
    chmod a+x "${script}"
    # pipelineSet CUR_SCRIPT ${script} 
    echo pipelineCreateStream task_SingleFrameDriver -1 CUR_SCRIPT="${script}"
  else
    raft_list=`sqlite3 ${OUTPUT_DATA_DIR}/registry.sqlite3 'select distinct raftName from raw where visit=174549'`
    for raftName in $raft_list; do
        script="${WORK_DIR}/02-process/script_${FILT}_${raftName}_$visit.sh"
  	build_singleframe_script "${script}" "${id} raftName=${raftName}"
  	chmod a+x "${script}"
  	# pipelineSet CUR_SCRIPT ${script} 
  	echo pipelineCreateStream task_SingleFrameDriver -1 CUR_SCRIPT="${script}"
    done
  fi
  #one full complete visit at nersc or cc : run makeFpSummary
done < ${VISIT_FILE}

