#!/bin/bash

# checkpoint
source ${SETUP_LOCATION}/checkpoint

BASEDIR=${IN_DIR}/work/${RERUN}/${streamID}
mkdir -p $BASEDIR
export BASEDIR

WORKDIR=${BASEDIR}/task_ingestion/${streamID}
mkdir -p ${WORKDIR}
export REGDIR=${WORKDIR}/registries
mkdir -p ${REGDIR}
export SCRDIR=${WORKDIR}/scripts
mkdir -p ${SCRDIR}
pipelineSet REGDIR ${REGDIR}
pipelineSet REGDIR ${SCRDIR}

build_ingest_script () {
    cat> $1.sh<<EOF
#!/bin/bash
DM_SETUP=${DM_SETUP}
source ${SETUP_LOCATION}/DMsetup.sh
export OMP_NUM_THREADS=1
if [[ \${SITE} == "NERSC" ]]
then
  ingestDriver.py ${IN_DIR} @$1 --cores 20 --mode link --output ${IN_DIR} -c clobber=True allowError=True register.ignore=True 
else
  cd \${TMPDIR}
  cp ${IN_DIR}/_mapper .
  ingestDriver.py . @$1 --cores \${NSLOTS} --output . --mode link
  mkdir -p ${IN_DIR}/raw
  cp -r raw/* ${IN_DIR}/raw/
  cp -r registry.sqlite3 $REGDIR/registry_\${JOB_ID}.sqlite3
fi
echo "{\"jobid\":\"\${JOB_ID}\", \"logfile\":\"\${JOBCONTROL_LOGFILE}\", \"script\":\"\${CUR_SCRIPT}\",  \"release\":\"\${DM_RELEASE}\",\"run\":\"\${RUN}\",\"tag\":\"\${SETUP_TAG}\",\"infile\":\"${RAW_VISIT_FILE}\"}" >> ${WORKDIR}/ingest_housekeeping.txt
EOF
}

VISITBASE=`basename ${RAW_VISIT_FILE} -s`
rm -f ${SCRDIR}/${VISITBASE}_chunk*

split -d -l ${RAW_CHUNKS} ${RAW_VISIT_FILE} ${SCRDIR}/${VISITBASE}_chunk

CHUNKFILES="${SCRDIR}/${VISITBASE}_chunk*"
cd ${SCRDIR}

for f in ${SCRDIR}/${VISITBASE}_chunk*
do
    build_ingest_script $f
    chmod a+x ${f}.sh
    pipelineCreateStream task_ingestData -1 CUR_SCRIPT=${f}.sh,REGDIR=${REGDIR}
done


