#!/bin/bash

# checkpoint
source ${SETUP_LOCATION}/checkpoint

if [[ $RERUN = *":"* ]]; then
    IFS=":" read RERUN1 RERUN2 <<< $RERUN
else
    RERUN2 = $RERUN
fi

cd ${WORK_DIR}/03-coadd

build_multiband_script () {
 cat> multiband_$1.sh<<EOF
#!/bin/bash
DM_SETUP=${DM_SETUP}
source ${SETUP_LOCATION}/DMsetup.sh
export OMP_NUM_THREADS=1
multiBandDriver.py $IN_DIR --rerun $RERUN2 --id tract=$1  --clobber-versions --cores=${NSLOTS}
EOF
}

while read tract; do
    build_multiband_script ${tract}
    chmod a+x multiband_${tract}.sh
    pipelineCreateStream task_multiBandDriver -1 CUR_SCRIPT=multiband_${tract}.sh
done <"scripts/tracts.list"

