#!/bin/bash

# checkpoint
source ${SETUP_LOCATION}/checkpoint

mkdir -p ${WORK_DIR}/02-processEimage
#cd ${WORK_DIR}/02-processEimage
#ln -sfn ${WORK_DIR} pardir
#ln -sfn ${DATA_DIR} datadir
#processEimage.py ${IN_DIR} --output ${OUT_DIR}

build_singleframe_script () {
 cat> $1<<EOF
#!/bin/bash
DM_SETUP=${DM_SETUP}
source ${SETUP_LOCATION}/DMsetup.sh
export OMP_NUM_THREADS=1
singleFrameDriver.py ${IN_DIR} --rerun ${RERUN} $2 --cores 8 --timeout 999999999 --configfile ${CONFIGS_LOCATION}/singleFrameDriverConfig_basicnocalib.py
EOF
}


for FILT in $(echo ${FILTERS} | tr "," "\n"); do 
  counter=0
  while read id; do
    echo $id
    counter=$[counter+1]
    if [[ $SITE == "LSST-IN2P3" ]]
    then
      #build script with one visit per processing
      script="${WORK_DIR}/02-processEimage/script_${FILT}_$counter.sh"
      build_singleframe_script "${script}" "${id}"
      chmod a+x "${script}"
      # pipelineSet CUR_SCRIPT ${script} 
      pipelineCreateStream task_SingleFrameDriver -1 CUR_SCRIPT="${script}"
    else
      for i in {0..4}; do
        for j in {0..4}; do
	  if [ "($i,$j)" != "(0,0)" -a "($i,$j)" != "(4,0)" -a "($i,$j)" != "(4,4)" -a "($i,$j)" != "(0,4)" ]; then
            script="${WORK_DIR}/02-processEimage/script_${FILT}_R${i}${j}_$counter.sh"
	    build_singleframe_script "${script}" "${id} raft=R${i}${j}"
	    chmod a+x "${script}"
	    # pipelineSet CUR_SCRIPT ${script} 
	    pipelineCreateStream task_SingleFrameDriver -1 CUR_SCRIPT="${script}"
          fi
        done
      done
    fi
    #one full complete visit at nersc or cc : run makeFpSummary
  done <"${WORK_DIR}/02-processEimage/${FILT}"_visit.list  
done
