#!/bin/bash

# checkpoint
source ${SETUP_LOCATION}/checkpoint

if [[ $RERUN = *":"* ]]; then
    IFS=":" read RERUN1 RERUN2 <<< $RERUN
else
    RERUN1=$RERUN
    RERUN2=$RERUN
fi
export RERUN1
export RERUN2


build_dark_script(){
 cat> $1<<EOF
#!/bin/bash
DM_SETUP=${DM_SETUP}
source ${SETUP_LOCATION}/DMsetup.sh
export OMP_NUM_THREADS=1
#
constructDark.py ${OUT_DIR} --rerun ${RERUN} --cores \${NSLOTS}
#
ingestCalib.py ${OUT_DIR} --output ${OUT_DIR}/CALIB --cores \${NSLOTS}
#
sqlite3 ${OUT_DIR}/CALIB/calibRegistry.sqlite3 "update dark set validStart='2021-01-01', validEnd='2033-01-01' where id>0;"
EOF
}

mkdir -p ${OUT_DIR}/rerun/${RERUN1}/scripts

script=${OUT_DIR}/rerun/${RERUN1}/scripts/dark.sh
build_dark_script ${script}
echo pipelineCreateStream task_dark -1 CUR_SCRIPT=${script}

