#!/bin/bash
export JARS=/home/descprod/Pipeline2/bsub/jars

export CLASSPATH=$JARS/org-srs-jobcontrol-2.1.0-jar-with-dependencies.jar
echo "CLASSPATH= $CLASSPATH"

ulimit -S -n 10000

mkdir -p /tmp/work
/usr/bin/rmiregistry & 

echo "GridEngine Setup"
source /usr/local/shared/bin/ge_env.sh

echo $SGE_ROOT
/usr/bin/java -verbose -Djava.util.logging.config.file=/home/descprod/Pipeline2/bsub/logging.grid.properties \
     -Dorg.srs.jobcontrol.ge.group="P_lsst_desc" \
     org.srs.jobcontrol.gridEngine.gridEngineJobControlService &
